/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proc4j_ProcessesFunctions */

#ifndef _Included_org_proc4j_ProcessesFunctions
#define _Included_org_proc4j_ProcessesFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_proc4j_ProcessesFunctions
 * Method:    list
 * Signature: ()[Lorg/proc4j/ProcessInfoNative;
 */
JNIEXPORT jobjectArray JNICALL Java_org_proc4j_ProcessesFunctions_list
  (JNIEnv *, jclass);

/*
 * Class:     org_proc4j_ProcessesFunctions
 * Method:    kill
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_proc4j_ProcessesFunctions_kill
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_proc4j_ProcessesFunctions
 * Method:    currentPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_proc4j_ProcessesFunctions_currentPid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
